LOG_PATH: &LOG_PATH logs/app.log
LOGGING:
  LEVEL: INFO
  FILE:
    LEVEL: INFO
    HANDLER:
      maxBytes: 1024 # 1MB = 1024 Bytes
      backupCount: 10 # max backup files
      filename: *LOG_PATH
    FORMATTER:
      #format
      fmt: "%(asctime)s - %(levelname)s - %(message)s"

  WS:
    LEVEL: NOTSET
    EVENT_NAME: new_log  # event name for adding a new log line at frontend
    NAMESPACE: logs  # namespace name for socketio handler
    FORMATTER:
      #format
      fmt: "%(asctime)s - %(levelname)s - %(message)s"
