version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: always 

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always

  app:
    build: .
    container_name: linker_app
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - app_network
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - app
    networks:
      - app_network
    restart: always

volumes:
  db_data:
  static_value:
  media_value:

networks:
  app_network:
    driver: bridge
