version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: linker_app_rabbit
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      service_net:

  prometheus:
    image: prom/prometheus
    container_name: linker_app_prometheus
    volumes:
      - ./prometheus_docker/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      service_net:

  grafana:
    image: grafana/grafana
    container_name: linker_app_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      service_net:

volumes:
  rabbitmq_data:
    driver: local
  grafana_data:
    driver: local
  prometheus-data:


networks:
  service_net:
    driver: bridge
