global:
  scrape_interval: 15s

#storage:
#  tsdb:
#    path: '/prometheus/data'
#    retention:
#      time: '7d'

scrape_configs:
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'rabbitmq:15692' ] # Change this to RabbitMQ container IP if needed


