"""empty message

Revision ID: 6315f81d5347
Revises: 
Create Date: 2023-08-02 13:14:55.036709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6315f81d5347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('domain_zone', sa.String(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('unavailable_times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_domain_zone'), ['domain_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_url'), ['url'], unique=True)
        batch_op.create_index(batch_op.f('ix_links_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_uuid'))
        batch_op.drop_index(batch_op.f('ix_links_url'))
        batch_op.drop_index(batch_op.f('ix_links_domain_zone'))

    op.drop_table('links')
    # ### end Alembic commands ###
