"""init revision

Revision ID: a673e36cc9a0
Revises: 
Create Date: 2023-07-25 20:10:34.534878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a673e36cc9a0"
down_revision = None
branch_labels = None
depends_on = None


EventType = sa.Enum(
    "status_changed",
    "resource_added",
    "resource_deleted",
    "photo_added",
    name="event_type",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_processing_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_urls", sa.Integer(), nullable=True),
        sa.Column("processed_urls", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("is_finished", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__file_processing_requests")),
    )
    op.create_table(
        "web_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=True),
        sa.Column("full_url", sa.String(), nullable=False),
        sa.Column("protocol", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("domain_zone", sa.String(), nullable=False),
        sa.Column("url_path", sa.String(), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=True),
        sa.Column("unavailable_count", sa.Integer(), nullable=True),
        sa.Column("screenshot", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__web_resources")),
    )
    op.create_index(
        op.f("ix__web_resources__domain_zone"),
        "web_resources",
        ["domain_zone"],
        unique=False,
    )
    op.create_index(
        op.f("ix__web_resources__full_url"), "web_resources", ["full_url"], unique=True
    )
    op.create_index(
        op.f("ix__web_resources__uuid"), "web_resources", ["uuid"], unique=False
    )
    op.create_table(
        "news_feed_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "STATUS_CHANGED",
                "RESOURCE_ADDED",
                "RESOURCE_DELETED",
                "PHOTO_ADDED",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["web_resources.id"],
            name=op.f("fk__news_feed_items__resource_id__web_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__news_feed_items")),
    )
    op.create_table(
        "web_resource_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "request_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["web_resources.id"],
            name=op.f("fk__web_resource_statuses__resource_id__web_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__web_resource_statuses")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_resource_statuses")
    op.drop_table("news_feed_items")
    op.drop_index(op.f("ix__web_resources__uuid"), table_name="web_resources")
    op.drop_index(op.f("ix__web_resources__full_url"), table_name="web_resources")
    op.drop_index(op.f("ix__web_resources__domain_zone"), table_name="web_resources")
    op.drop_table("web_resources")
    op.drop_table("file_processing_requests")
    # ### end Alembic commands ###
    EventType.drop(op.get_bind(), checkfirst=False)
