"""empty message

Revision ID: 976f535f6d32
Revises: 
Create Date: 2023-07-29 14:32:08.680546

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "976f535f6d32"
down_revision = None
branch_labels = None
depends_on = None

EventType = sa.Enum(
    "status_changed",
    "resource_added",
    "resource_deleted",
    "photo_added",
    name="event_type",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("full_url", sa.String(length=255), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("domain_zone", sa.String(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=True),
        sa.Column("unavailable_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__links")),
    )
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix__links__domain_zone"), ["domain_zone"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix__links__full_url"), ["full_url"], unique=True
        )
        batch_op.create_index(batch_op.f("ix__links__uuid"), ["uuid"], unique=False)

    op.create_table(
        "link_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "request_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["link_id"], ["links.id"], name=op.f("fk__link_responses__link_id__links")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__link_responses")),
    )
    op.create_table(
        "links_screenshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.Column("screenshot", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["links.id"],
            name=op.f("fk__links_screenshots__link_id__links"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__links_screenshots")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links_screenshots")
    op.drop_table("link_responses")
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix__links__uuid"))
        batch_op.drop_index(batch_op.f("ix__links__full_url"))
        batch_op.drop_index(batch_op.f("ix__links__domain_zone"))

    op.drop_table("links")
    EventType.drop
    # ### end Alembic commands ###
